base_config: chasing_3_chase_1_traditional_pose_controller

experiment:
  name: chasing_traditional_pose_60hz_multihead
  seed: 42
  tags:
    - traditional-pid
    - control-hz
    - 60hz
    - critic-multihead

unity:
  env_base_port: 4600
  num_envs: 1 # test only

trainer:
  backend: marl
  overrides:
    critic_variant: critic_multihead
    overwrite: true
    enable_yaw_control: true
    body_pid_control_rate_hz: 60.0
    num_eval_envs: 1 # test only
