task_config: task_v1.yaml
action_contract: wrench4_v1

experiment:
  name: gail_goal_yaw_wrench4_v1
  seed: 42
  output_dir: ../../../artifacts/runs/irl/goal_yaw/gail_wrench4_v1

env:
  unity:
    env_path: ../../../artifacts/unity_builds/irl/linux/GoalYawIRL_Fossen_10Hz_Server/GoalYawIRL.x86_64
    env_base_port: 26225
    port_offset: 0
    no_graphics: true
    timeout_wait: 300
    parallel_mode: multi_binary
  train:
    num_envs: 8
    time_scale: 10.0
  eval:
    num_envs: 1
    time_scale: 1.0
    num_episodes: 200

algorithm:
  name: gail
  total_timesteps: 5000000
  demo_batch_size: 256
  n_disc_updates_per_round: 4
  ppo_n_steps: 512
  ppo_batch_size: 256
  ppo_n_epochs: 10
  learning_rate: 0.0003
  gamma: 0.99
  device: auto
