experiment:
  name: finsrov_hold_for_position_wrench_skrl
  seed: 42
  tags: [isaaclab, finsrov, hold_for_position, wrench, skrl]
  output_dir: null

isaaclab:
  path: ${ISAACLAB_PATH}
  task: FinsSim-FinsROV-HoldForPosition-Wrench-v0
  rl_library: skrl
  cuda_visible_devices: "1"
  device: cuda:0
  num_envs: 2048
  max_iterations: 400
  headless: true
  video: false
  hydra_overrides: []

train:
  resume_checkpoint: null

play:
  checkpoint: null
  num_envs: 1
  headless: false
  real_time: false
  video: false
