base_config: ppo_wrench_for_pose_empirical_thruster_mixer

experiment:
  name: ppo_wrench_for_hold_position_fossen_parallel_eval
  seed: 42
  tags: [ppo, hold_for_position, wrench_control, fossen6dof, training_area_replicator, eval]
  # output_dir: artifacts/evals/rl/hold_for_position/ppo_wrench_for_hold_position_fossen_parallel
  # output_dir: ./artifacts/runs/rl/hold_for_position/wrench/ppo_wrench_for_hold_position_fossen_parallel_1024_15s_0815
  # output_dir: ./artifacts/runs/rl/hold_for_position/wrench/ppo_wrench_for_hold_position_fossen_parallel_1024_15s_init_0815
  output_dir: ./artifacts/runs/rl/hold_for_position/wrench/ppo_wrench_for_hold_position_fossen_parallel_1024_15s_learn_to_swim_dense

env:
  unity:
    env_path: ../../artifacts/unity_builds/rl/linux/HoldForPosition_Fossen_Parallel_10Hz_Server/HoldForPosition_Parallel.x86_64
    env_base_port: 38105
    port_offset: 0
    no_graphics: true
    timeout_wait: 600
    parallel_mode: multi_area

  eval:
    num_envs: 1
    # Total completed episodes across all eval areas, not per area.
    num_episodes: 5
    time_scale: 1.0
    mode: asynchronous

trainer:
  backend: rl
  overrides:
    device: cuda
    # 直接指定要评估的单个 checkpoint 文件；可替换为 best_model.zip、final_model.zip
    # 或 checkpoints 目录中的任意中途 checkpoint。
    # checkpoint_path: ./artifacts/runs/rl/hold_for_position/wrench/ppo_wrench_for_hold_position_fossen_parallel_1024_15s_learn_to_swim_dense/checkpoints/ppo_wrench_underwater_model_7372800_steps.zip
    checkpoint_path: ./artifacts/runs/rl/hold_for_position/wrench/ppo_wrench_for_hold_position_fossen_15s_learn_to_swim_dense_from_new_reward_to_100m/checkpoints/ppo_wrench_underwater_model_87687168_steps.zip
