from __future__ import annotations

import argparse
import math
import time
from pathlib import Path
from typing import Any

import numpy as np
import yaml

from state_estimation.transforms import (
    matrix_to_pose,
    pose_matrix,
    quat_multiply_xyzw,
    quat_to_rpy_xyzw,
    rpy_to_quat_xyzw,
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Calibrate T_world_camera from known world tag poses and AprilTag PnP detections."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    capture = subparsers.add_parser("capture", help="Collect T_camera_tag samples from a ROS PnP topic.")
    capture.add_argument("--world-tags", required=True, help="YAML containing known T_world_tag poses.")
    capture.add_argument("--samples", required=True, help="Output sample YAML path.")
    capture.add_argument("--topic", default="/finsrov/vision/tag_poses_3d_camera")
    capture.add_argument("--count", type=int, default=80, help="Total samples to collect.")
    capture.add_argument("--duration-sec", type=float, default=0.0, help="Optional max capture time. 0 disables.")
    capture.add_argument("--min-interval-sec", type=float, default=0.10)
    capture.add_argument("--max-reprojection-error-px", type=float, default=4.0)
    capture.add_argument("--append", action="store_true", help="Append to existing sample YAML.")

    capture_point = subparsers.add_parser(
        "capture-point",
        help="Collect samples for one movable AprilTag placed at one known world pose.",
    )
    capture_point.add_argument("--samples", required=True, help="Output sample YAML path.")
    capture_point.add_argument("--topic", default="/finsrov/vision/tag_poses_3d_camera")
    capture_point.add_argument("--tag-id", type=int, required=True, help="The movable tag ID to use.")
    capture_point.add_argument("--world-xyz", type=float, nargs=3, required=True, metavar=("X", "Y", "Z"))
    capture_point.add_argument("--world-rpy-deg", type=float, nargs=3, default=[0.0, 0.0, 0.0], metavar=("R", "P", "Y"))
    capture_point.add_argument("--world-quat-xyzw", type=float, nargs=4, default=None, metavar=("X", "Y", "Z", "W"))
    capture_point.add_argument("--point-name", default="", help="Optional label stored in the sample file.")
    capture_point.add_argument("--count", type=int, default=40, help="Samples to collect at this point.")
    capture_point.add_argument("--duration-sec", type=float, default=0.0, help="Optional max capture time. 0 disables.")
    capture_point.add_argument("--min-interval-sec", type=float, default=0.10)
    capture_point.add_argument("--max-reprojection-error-px", type=float, default=4.0)
    capture_point.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite the sample file instead of appending. By default capture-point appends.",
    )

    solve = subparsers.add_parser("solve", help="Solve T_world_camera from a sample YAML.")
    solve.add_argument("--samples", required=True, help="Sample YAML generated by capture.")
    solve.add_argument("--output", required=True, help="Output YAML containing solved T_world_camera.")
    solve.add_argument(
        "--update-extrinsics",
        default="",
        help="Optional state_fusion_extrinsics.yaml to update in place.",
    )
    solve.add_argument("--ransac", action="store_true", help="Reject translation outliers before final averaging.")
    solve.add_argument("--ransac-threshold-m", type=float, default=0.08)
    solve.add_argument(
        "--point-cloud",
        action="store_true",
        help="Solve full T_world_camera from tag center point correspondences, ignoring tag local orientation.",
    )

    args = parser.parse_args()
    if args.command == "capture":
        capture_samples(args)
    elif args.command == "capture-point":
        capture_point_samples(args)
    elif args.command == "solve":
        solve_extrinsic(args)


def capture_samples(args: argparse.Namespace) -> None:
    import rclpy
    from msgs.msg import AprilTagDetection3DArray
    from rclpy.node import Node

    world_tags = load_world_tags(Path(args.world_tags))
    samples_path = Path(args.samples)
    samples = load_samples(samples_path) if args.append and samples_path.exists() else []
    last_sample_time_by_tag: dict[int, float] = {}

    rclpy.init()
    node = Node("world_camera_extrinsic_capture")

    def callback(msg: AprilTagDetection3DArray) -> None:
        nonlocal samples
        now_monotonic = time.monotonic()
        stamp_sec = float(msg.header.stamp.sec) + float(msg.header.stamp.nanosec) * 1e-9
        if stamp_sec <= 0.0:
            stamp_sec = node.get_clock().now().nanoseconds * 1e-9
        for detection in msg.detections:
            tag_id = int(detection.tag_id)
            if tag_id not in world_tags:
                continue
            if (
                args.max_reprojection_error_px > 0.0
                and float(detection.reprojection_error_px) > args.max_reprojection_error_px
            ):
                continue
            if now_monotonic - last_sample_time_by_tag.get(tag_id, -1e9) < args.min_interval_sec:
                continue
            pose = detection.pose.pose
            sample = {
                "stamp_sec": float(stamp_sec),
                "tag_id": tag_id,
                "T_world_tag": transform_to_yaml(world_tags[tag_id]),
                "T_camera_tag": {
                    "translation_xyz": [
                        float(pose.position.x),
                        float(pose.position.y),
                        float(pose.position.z),
                    ],
                    "rotation_xyzw": [
                        float(pose.orientation.x),
                        float(pose.orientation.y),
                        float(pose.orientation.z),
                        float(pose.orientation.w),
                    ],
                },
                "decision_margin": float(detection.decision_margin),
                "reprojection_error_px": float(detection.reprojection_error_px),
            }
            samples.append(sample)
            last_sample_time_by_tag[tag_id] = now_monotonic
            write_samples(samples_path, samples)
            print(
                f"sample {len(samples)}/{args.count}: tag={tag_id} "
                f"reproj={float(detection.reprojection_error_px):.3f}px"
            )
            if len(samples) >= args.count:
                rclpy.shutdown()
                return

    node.create_subscription(AprilTagDetection3DArray, args.topic, callback, 10)
    print(f"listening: {args.topic}")
    print(f"known tags: {sorted(world_tags)}")
    print(f"samples: {samples_path}")
    start = time.monotonic()
    try:
        while rclpy.ok():
            rclpy.spin_once(node, timeout_sec=0.1)
            if args.duration_sec > 0.0 and time.monotonic() - start >= args.duration_sec:
                break
    except KeyboardInterrupt:
        pass
    finally:
        if rclpy.ok():
            rclpy.shutdown()
        node.destroy_node()
    print(f"saved {len(samples)} samples to {samples_path}")


def capture_point_samples(args: argparse.Namespace) -> None:
    import rclpy
    from msgs.msg import AprilTagDetection3DArray
    from rclpy.node import Node

    samples_path = Path(args.samples)
    samples = [] if args.overwrite or not samples_path.exists() else load_samples(samples_path)
    initial_sample_count = len(samples)
    collected_count = 0
    last_sample_time = -1e9
    last_seen_print_time = -1e9
    t_world_tag = pose_matrix(
        args.world_xyz,
        args.world_quat_xyzw
        if args.world_quat_xyzw is not None
        else rpy_to_quat_xyzw(*[math.radians(float(v)) for v in args.world_rpy_deg]),
    )
    target_tag_id = int(args.tag_id)

    rclpy.init()
    node = Node("world_camera_extrinsic_capture_point")

    def callback(msg: AprilTagDetection3DArray) -> None:
        nonlocal samples, collected_count, last_sample_time, last_seen_print_time
        now_monotonic = time.monotonic()
        seen_ids = [int(detection.tag_id) for detection in msg.detections]
        target_detections = [detection for detection in msg.detections if int(detection.tag_id) == target_tag_id]
        if not target_detections:
            if now_monotonic - last_seen_print_time >= 1.0:
                print(f"seen_ids={seen_ids}; using tag_id={target_tag_id}; waiting for target tag")
                last_seen_print_time = now_monotonic
            return

        detection = min(target_detections, key=lambda item: float(item.reprojection_error_px))
        reprojection_error = float(detection.reprojection_error_px)
        if args.max_reprojection_error_px > 0.0 and reprojection_error > args.max_reprojection_error_px:
            if now_monotonic - last_seen_print_time >= 1.0:
                print(
                    f"seen_ids={seen_ids}; using tag_id={target_tag_id}; "
                    f"reject reproj={reprojection_error:.3f}px"
                )
                last_seen_print_time = now_monotonic
            return
        if now_monotonic - last_sample_time < args.min_interval_sec:
            return

        stamp_sec = float(msg.header.stamp.sec) + float(msg.header.stamp.nanosec) * 1e-9
        if stamp_sec <= 0.0:
            stamp_sec = node.get_clock().now().nanoseconds * 1e-9
        samples.append(
            make_sample(
                stamp_sec=stamp_sec,
                tag_id=target_tag_id,
                t_world_tag=t_world_tag,
                detection=detection,
                source="capture-point",
                point_name=args.point_name,
            )
        )
        collected_count += 1
        last_sample_time = now_monotonic
        write_samples(samples_path, samples)
        print(
            f"point_sample {collected_count}/{args.count}: seen_ids={seen_ids}; "
            f"using tag_id={target_tag_id}; reproj={reprojection_error:.3f}px; total={len(samples)}"
        )
        if collected_count >= args.count:
            rclpy.shutdown()

    node.create_subscription(AprilTagDetection3DArray, args.topic, callback, 10)
    print(f"listening: {args.topic}")
    print(f"samples: {samples_path}")
    print(f"mode: movable single tag point; using tag_id={target_tag_id}")
    print(f"world_xyz: {[float(v) for v in args.world_xyz]}")
    if args.world_quat_xyzw is not None:
        print(f"world_quat_xyzw: {[float(v) for v in args.world_quat_xyzw]}")
    else:
        print(f"world_rpy_deg: {[float(v) for v in args.world_rpy_deg]}")
    print(f"existing_samples: {initial_sample_count}; overwrite={args.overwrite}")

    start = time.monotonic()
    try:
        while rclpy.ok():
            rclpy.spin_once(node, timeout_sec=0.1)
            if args.duration_sec > 0.0 and time.monotonic() - start >= args.duration_sec:
                break
    except KeyboardInterrupt:
        pass
    finally:
        if rclpy.ok():
            rclpy.shutdown()
        node.destroy_node()
    print(f"saved {collected_count} new samples; total={len(samples)} in {samples_path}")


def solve_extrinsic(args: argparse.Namespace) -> None:
    samples = load_samples(Path(args.samples))
    if len(samples) < 3:
        raise SystemExit("at least 3 samples are recommended to solve T_world_camera")

    if args.point_cloud:
        t_world_camera, inlier_indices, report = solve_point_cloud(samples, args.ransac, args.ransac_threshold_m)
        output = {
            "T_world_camera": transform_to_yaml(t_world_camera),
            "solve_mode": "point_cloud",
            "sample_count": len(samples),
            "inlier_count": len(inlier_indices),
            "translation_rmse_m": report["translation_rmse_m"],
            "translation_max_error_m": report["translation_max_error_m"],
        }
        write_yaml(Path(args.output), output)
        print_report(output)
        if args.update_extrinsics:
            update_state_fusion_extrinsics(Path(args.update_extrinsics), t_world_camera)
            print(f"updated T_world_camera in {args.update_extrinsics}")
        return

    estimates = []
    for sample in samples:
        t_world_tag = parse_transform_node(sample["T_world_tag"], "T_world_tag")
        t_camera_tag = parse_transform_node(sample["T_camera_tag"], "T_camera_tag")
        estimates.append(t_world_tag @ np.linalg.inv(t_camera_tag))

    inlier_indices = list(range(len(estimates)))
    if args.ransac:
        preliminary = average_transforms(estimates)
        preliminary_translation = preliminary[:3, 3]
        inlier_indices = [
            index
            for index, estimate in enumerate(estimates)
            if np.linalg.norm(estimate[:3, 3] - preliminary_translation) <= args.ransac_threshold_m
        ]
        if len(inlier_indices) < 3:
            raise SystemExit("RANSAC rejected too many samples; check world tag poses and PnP detections")

    inlier_estimates = [estimates[index] for index in inlier_indices]
    t_world_camera = average_transforms(inlier_estimates)
    report = build_report(t_world_camera, [samples[index] for index in inlier_indices])
    output = {
        "T_world_camera": transform_to_yaml(t_world_camera),
        "sample_count": len(samples),
        "inlier_count": len(inlier_indices),
        "translation_rmse_m": report["translation_rmse_m"],
        "translation_max_error_m": report["translation_max_error_m"],
        "rotation_rmse_deg": report["rotation_rmse_deg"],
        "rotation_max_error_deg": report["rotation_max_error_deg"],
    }
    write_yaml(Path(args.output), output)
    print_report(output)

    if args.update_extrinsics:
        update_state_fusion_extrinsics(Path(args.update_extrinsics), t_world_camera)
        print(f"updated T_world_camera in {args.update_extrinsics}")


def solve_point_cloud(
    samples: list[dict[str, Any]],
    use_ransac: bool,
    threshold_m: float,
) -> tuple[np.ndarray, list[int], dict[str, float]]:
    camera_points, world_points = sample_position_arrays(samples)
    transform = rigid_transform_from_points(camera_points, world_points)
    inlier_indices = list(range(len(samples)))
    if use_ransac:
        residuals = position_residuals(transform, camera_points, world_points)
        inlier_indices = [index for index, residual in enumerate(residuals) if residual <= threshold_m]
        if len(inlier_indices) < 3:
            raise SystemExit("point-cloud RANSAC rejected too many samples; check world xyz and PnP detections")
        transform = rigid_transform_from_points(camera_points[inlier_indices], world_points[inlier_indices])
    residuals = position_residuals(transform, camera_points[inlier_indices], world_points[inlier_indices])
    return transform, inlier_indices, {
        "translation_rmse_m": float(np.sqrt(np.mean(residuals * residuals))),
        "translation_max_error_m": float(np.max(residuals)),
    }


def sample_position_arrays(samples: list[dict[str, Any]]) -> tuple[np.ndarray, np.ndarray]:
    camera_points = []
    world_points = []
    for sample in samples:
        camera_points.append(parse_transform_node(sample["T_camera_tag"], "T_camera_tag")[:3, 3])
        world_points.append(parse_transform_node(sample["T_world_tag"], "T_world_tag")[:3, 3])
    return np.asarray(camera_points, dtype=np.float64), np.asarray(world_points, dtype=np.float64)


def rigid_transform_from_points(camera_points: np.ndarray, world_points: np.ndarray) -> np.ndarray:
    if camera_points.shape != world_points.shape or camera_points.shape[0] < 3:
        raise ValueError("camera/world point arrays must have shape Nx3 with N >= 3")
    camera_centroid = np.mean(camera_points, axis=0)
    world_centroid = np.mean(world_points, axis=0)
    camera_centered = camera_points - camera_centroid
    world_centered = world_points - world_centroid
    covariance = camera_centered.T @ world_centered
    u, _, vt = np.linalg.svd(covariance)
    rotation = vt.T @ u.T
    if np.linalg.det(rotation) < 0.0:
        vt[-1, :] *= -1.0
        rotation = vt.T @ u.T
    translation = world_centroid - rotation @ camera_centroid
    transform = np.eye(4, dtype=np.float64)
    transform[:3, :3] = rotation
    transform[:3, 3] = translation
    return transform


def position_residuals(transform: np.ndarray, camera_points: np.ndarray, world_points: np.ndarray) -> np.ndarray:
    predicted = (transform[:3, :3] @ camera_points.T).T + transform[:3, 3]
    return np.linalg.norm(predicted - world_points, axis=1)


def load_world_tags(path: Path) -> dict[int, np.ndarray]:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    container = data.get("T_world_tag", data.get("tags", data))
    tags: dict[int, np.ndarray] = {}
    for key, node in container.items():
        tags[int(key)] = parse_transform_node(node, f"T_world_tag.{key}")
    if not tags:
        raise SystemExit(f"no world tag poses found in {path}")
    return tags


def load_samples(path: Path) -> list[dict[str, Any]]:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    samples = data.get("samples", [])
    if not isinstance(samples, list):
        raise SystemExit(f"{path} must contain a samples list")
    return samples


def write_samples(path: Path, samples: list[dict[str, Any]]) -> None:
    write_yaml(path, {"samples": samples})


def write_yaml(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=True), encoding="utf-8")


def make_sample(
    *,
    stamp_sec: float,
    tag_id: int,
    t_world_tag: np.ndarray,
    detection,
    source: str,
    point_name: str = "",
) -> dict[str, Any]:
    pose = detection.pose.pose
    sample = {
        "stamp_sec": float(stamp_sec),
        "tag_id": int(tag_id),
        "T_world_tag": transform_to_yaml(t_world_tag),
        "T_camera_tag": {
            "translation_xyz": [
                float(pose.position.x),
                float(pose.position.y),
                float(pose.position.z),
            ],
            "rotation_xyzw": [
                float(pose.orientation.x),
                float(pose.orientation.y),
                float(pose.orientation.z),
                float(pose.orientation.w),
            ],
        },
        "decision_margin": float(detection.decision_margin),
        "reprojection_error_px": float(detection.reprojection_error_px),
        "source": source,
    }
    if point_name:
        sample["point_name"] = point_name
    return sample


def parse_transform_node(node: dict[str, Any], name: str) -> np.ndarray:
    if "matrix" in node:
        return np.asarray(node["matrix"], dtype=np.float64).reshape(4, 4)
    translation = node.get("translation_xyz", [0.0, 0.0, 0.0])
    if "rotation_xyzw" in node:
        rotation = node["rotation_xyzw"]
    elif "rotation_rpy_deg" in node:
        rotation = rpy_to_quat_xyzw(*[math.radians(float(v)) for v in node["rotation_rpy_deg"]])
    elif "rotation_rpy_rad" in node:
        rotation = rpy_to_quat_xyzw(*[float(v) for v in node["rotation_rpy_rad"]])
    else:
        rotation = [0.0, 0.0, 0.0, 1.0]
    try:
        return pose_matrix(translation, rotation)
    except Exception as exc:  # noqa: BLE001
        raise ValueError(f"invalid transform {name}") from exc


def transform_to_yaml(transform: np.ndarray) -> dict[str, list[float]]:
    translation, quat = matrix_to_pose(transform)
    return {
        "translation_xyz": [float(v) for v in translation],
        "rotation_xyzw": [float(v) for v in quat],
    }


def average_transforms(transforms: list[np.ndarray]) -> np.ndarray:
    translations = np.asarray([transform[:3, 3] for transform in transforms], dtype=np.float64)
    quaternions = np.asarray([matrix_to_pose(transform)[1] for transform in transforms], dtype=np.float64)
    reference = quaternions[0]
    for index in range(len(quaternions)):
        if float(np.dot(reference, quaternions[index])) < 0.0:
            quaternions[index] *= -1.0
    accumulator = np.zeros((4, 4), dtype=np.float64)
    for quat in quaternions:
        accumulator += np.outer(quat, quat)
    eigenvalues, eigenvectors = np.linalg.eigh(accumulator)
    average_quat = eigenvectors[:, int(np.argmax(eigenvalues))]
    if average_quat[3] < 0.0:
        average_quat *= -1.0
    return pose_matrix(np.mean(translations, axis=0), average_quat)


def build_report(t_world_camera: np.ndarray, samples: list[dict[str, Any]]) -> dict[str, float]:
    translation_errors = []
    rotation_errors = []
    for sample in samples:
        expected = parse_transform_node(sample["T_world_tag"], "T_world_tag")
        observed = parse_transform_node(sample["T_camera_tag"], "T_camera_tag")
        predicted = t_world_camera @ observed
        translation_errors.append(float(np.linalg.norm(predicted[:3, 3] - expected[:3, 3])))
        _, predicted_quat = matrix_to_pose(predicted)
        _, expected_quat = matrix_to_pose(expected)
        delta = quat_multiply_xyzw(predicted_quat, [-expected_quat[0], -expected_quat[1], -expected_quat[2], expected_quat[3]])
        angle = 2.0 * math.atan2(np.linalg.norm(delta[:3]), abs(float(delta[3])))
        rotation_errors.append(math.degrees(abs(angle)))
    translation = np.asarray(translation_errors, dtype=np.float64)
    rotation = np.asarray(rotation_errors, dtype=np.float64)
    return {
        "translation_rmse_m": float(np.sqrt(np.mean(translation * translation))),
        "translation_max_error_m": float(np.max(translation)),
        "rotation_rmse_deg": float(np.sqrt(np.mean(rotation * rotation))),
        "rotation_max_error_deg": float(np.max(rotation)),
    }


def update_state_fusion_extrinsics(path: Path, t_world_camera: np.ndarray) -> None:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) if path.exists() else {}
    if data is None:
        data = {}
    data["T_world_camera"] = transform_to_yaml(t_world_camera)
    write_yaml(path, data)


def print_report(output: dict[str, Any]) -> None:
    transform = output["T_world_camera"]
    roll, pitch, yaw = quat_to_rpy_xyzw(transform["rotation_xyzw"])
    print("Solved T_world_camera")
    print(f"solve_mode: {output.get('solve_mode', 'full_pose')}")
    print(f"sample_count: {output['sample_count']}")
    print(f"inlier_count: {output['inlier_count']}")
    print(f"translation_xyz: {[round(v, 6) for v in transform['translation_xyz']]}")
    print(f"rotation_xyzw: {[round(v, 8) for v in transform['rotation_xyzw']]}")
    print(f"rotation_rpy_deg: {[round(math.degrees(v), 3) for v in (roll, pitch, yaw)]}")
    print(f"translation_rmse_m: {output['translation_rmse_m']:.6f}")
    print(f"translation_max_error_m: {output['translation_max_error_m']:.6f}")
    if "rotation_rmse_deg" in output:
        print(f"rotation_rmse_deg: {output['rotation_rmse_deg']:.3f}")
        print(f"rotation_max_error_deg: {output['rotation_max_error_deg']:.3f}")


if __name__ == "__main__":
    main()
